### ISSUE TITLE
How to open SPE1 case tutorial

### ISSUE THREAD

**Issue by davincr** [OPM/opm-data-legacy#132]
Hi,

Does anyone know how to open SPE1 case using windows platform? I've already typed the directory as mentioned on the tutorial. However, it somehow doesn't work and just leaves me with the message no such file or directory.(As you can see in the attachment)
![opm1](https://cloud.githubusercontent.com/assets/21306653/18046730/6b4e16ea-6e03-11e6-821f-8b5b1b61a606.PNG)

**Comment by atgeirr** [comment]
To be clear, did you encounter the problem while following the tutorial here?

http://opm-project.org/?page_id=294

**Comment by davincr** [comment]
Hi,
Thanks for the answer. No, I didn't encouter any problems while following the tutorial (until page 5). The problem started when I tried to run the flow simulation because somehow the files can't be opened.

**Comment by atgeirr** [comment]
You cannot find the files because they do not exist _on the virtual machine_. You must either install them (by git-cloning opm-data for example), or place them in a location on the host computer that is accessible from the VM. One such location that is already setup is the "/host" directory on the VM, it is linked to the directory on the host from which you ran vagrant. If you do

``` sh
cd /host
ls
```

you should see the contents (containing the VagrantFile for example). If you place the deck and its included files there you can run flow with it.

If you have plenty of disk and a good internet connection it can be just as convenient to clone opm-data inside the VM. If not, and you cannot for some reason place your datafiles in the directory linked to "/host" you must read the vagrant docs to see how you can link any host directory to the VM.

**Comment by davincr** [comment]
Okay thank you!. I will try that way. Maybe can you explain more how to place them in location that is accessible from the VM? (Like you create folder and open it directly from the software (I installed oracle vm)?? or just type that command on the command window).Sorry, I am little bit confused.

**Comment by atgeirr** [comment]
You must read the documentation for your virtual machine to find out how to set up a link to host.

I have updated slightly the [Windows/VM tutorial](http://opm-project.org/?page_id=294), it now states explicitly (after the `vagrant ssh` command) that you should start with step 3 of the [My first simulation](http://opm-project.org/?page_id=197) tutorial. Follow that and you should have no problems.

**Comment by davincr** [comment]
Thank you. I will try it.  I also tried to use thiscommand

cd /host
ls

I was able to see the contents that you mentioned before (bootstrap, VagrantFile and also the folder spe1 since I put on the same folder), Could you explain from this point? How can I continue and open the file ? Because I tried again using
 cd opm-data-master/spe1
It didn't work although the file is there when I typed cd/host. Maybe there are another commands?

Sorry for a lot of question since OPM is really a new environment for me.

**Comment by atgeirr** [comment]
I am sorry, but I do not quite see what your problem is. If you are new to linux or unix-type environments I suggest you pick up a tutorial on that. Did you follow exactly the steps of both tutorials?

**Comment by davincr** [comment]
Yes. I followed exactly.  But the problem is still similar that the virtual box cannot locate the file. Although I tried to link the virtual box with the opm data master by using shared folder option in the virtual box. Is there any possibilities that windows version may have sort effect here? I'm using windows 10.

**Comment by atgeirr** [comment]
If you run the My first simulation tutorial (starting with step 3) _from the virtual machine_ (i.e. after `vagrant ssh`) it should work. Does not the git clone command work?

While we have not checked that it works with Windows 10, it should not matter since you are doing things in the virtual machine which runs Ubuntu Linux.

**Comment by davincr** [comment]
I didn't use git clone. I just downloaded it as a zip and saved it on my desired folder. Yes until the point vagrant ssh, it was working then even I typed the command flow. However, when I try to open the file using 
cd opm-data-master/spe1 or even 
cd ~/
wget https://github.com/OPM/opm-data/archive/master.zip "The file directory is

It was not working : no such file or directory
